#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage.
# This is the cookie function later..
if [[ -t 0 || -t 1 ]]; then
  if (( $+commands[fortune] )); then
    if (( $+commands[lolcat] )); then
      if (( $+commands[unisay] )); then
        fortune -s | unisay -C | lolcat
      else
        fortune -s | lolcat
      fi
    else
      fortune -s
    fi
  else
    echo "Well, no cookies for you.. :c"
  fi
  print
fi


